"""
Routine Convert settings


Summary
-------
Common variables to be used throughout module should live in this spot.


Required to run
--------
BINARIES (2):       "HandBrakeCLI.exe", "ffprobe.exe"
PRESET FILE (1):    presets.json (generated by Handbrake)
root_dir:           Needs to point to a "media folder" on your system!  (ex.  "C:\BluRay_Files")
"""

import os

# Separators
EMP_SEP = ''
SPC_SEP = ' '
USCORE_SEP = '_'
DASH_SEP = '-'
WIDE_DASH_SEP = DASH_SEP.join([' ', ' '])  # result: ' - '


# Media (MakeMKV) directories
root_dir = r"D:\MakeMKV_Rips"

# @ryan Note:
# Originally, I specified a general "binary folder" is where I place the required binaries for
# this module.  Even if there's only one, or a few, required by the module - it's convenient to have
# them under one spot! :)
BIN_DIR = os.path.normpath(os.path.join(os.path.dirname(__file__), 'bin'))  # Ex:  C:\site-packages\routine_convert\bin

# BINARIES
# =================================
# Path to Hand-brake CLI
# (CLI version, to run conversion:  https://handbrake.fr/downloads2.php)
HB_BIN = os.path.join(BIN_DIR, "HandBrakeCLI.exe")  # Ex:  C:\site-packages\routine_convert\bin\HandBrakeCLI.exe

# Not required: (GUI version, for ease-of-use to make presets/do single tasks: https://handbrake.fr/downloads.php)

# Path to ffprobe
# (part of ffmpeg: https://ffmpeg.zeranoe.com/builds/)
FFPROBE = os.path.join(BIN_DIR, "ffprobe.exe")  # Ex:  C:\site-packages\routine_convert\bin\ffprobe.exe
FFPROBE_FMT_STR = 'format'
FFPROBE_TAG_STR = 'tags'

# PRESET FILE
# =================================
# Handbrake setting location (this is made by loading up the GUI version of the program)
# Ex:   C:\users\yourname\AppData\HandBrake\presets.json
PRESET_FILE = os.path.join(os.environ['AppData'], r"HandBrake\presets.json")

# DISC FORMATS
# =================================
# Physical disc formats (used as sub-folders to look in)
DISC_FORMATS = {
    'dvd': 'DVD',
    'bluray': 'Blu-Ray',
}

print(BIN_DIR)
